import { Injectable, InternalServerErrorException } from '@nestjs/common';
import * as crypto from 'crypto';

@Injectable()
export class EncryptionService {
  private readonly algorithm = 'aes-256-gcm';
  private readonly key: Buffer;

  constructor() {
    const keyHex = process.env.ENCRYPTION_MASTER_KEY;
    if (!keyHex || keyHex.length !== 64) {
      throw new InternalServerErrorException(
        'ENCRYPTION_MASTER_KEY must be a 64 character hex string (32 bytes).',
      );
    }
    this.key = Buffer.from(keyHex, 'hex');
  }

  /**
   * Encrypts plaintext using AES-256-GCM with a random IV.
   * Returns a formatted string: iv:authTag:ciphertext (all in hex).
   */
  encrypt(plainText: string): string {
    if (!plainText) return plainText;
    
    const iv = crypto.randomBytes(12); // 96 bits for GCM
    const cipher = crypto.createCipheriv(this.algorithm, this.key, iv);
    
    let encrypted = cipher.update(plainText, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    const authTag = cipher.getAuthTag().toString('hex');
    
    return `${iv.toString('hex')}:${authTag}:${encrypted}`;
  }

  /**
   * Decrypts ciphertext that was generated by `encrypt` or `encryptDeterministic`.
   */
  decrypt(cipherText: string): string {
    if (!cipherText || !cipherText.includes(':')) return cipherText;

    const parts = cipherText.split(':');
    if (parts.length !== 3) {
      throw new Error('Invalid encrypted text format.');
    }

    const [ivHex, authTagHex, encryptedHex] = parts;
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');

    const decipher = crypto.createDecipheriv(this.algorithm, this.key, iv);
    decipher.setAuthTag(authTag);

    try {
      let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
      decrypted += decipher.final('utf8');
      return decrypted;
    } catch (e) {
      throw new Error('Decryption failed: integrity check or bad data.');
    }
  }

  /**
   * Encrypts plaintext deterministically (same input always produces same output).
   * Useful for searchable exact-match fields like phone numbers.
   * Uses HMAC of the plaintext to generate a stable IV.
   */
  encryptDeterministic(plainText: string): string {
    if (!plainText) return plainText;

    // Generate a stable IV based on the plaintext and key
    const hmac = crypto.createHmac('sha256', this.key);
    hmac.update(plainText);
    const stableIv = hmac.digest().subarray(0, 12);

    const cipher = crypto.createCipheriv(this.algorithm, this.key, stableIv);
    
    let encrypted = cipher.update(plainText, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    const authTag = cipher.getAuthTag().toString('hex');
    
    return `${stableIv.toString('hex')}:${authTag}:${encrypted}`;
  }
}
